### PR TITLE
Update TFM_Util.java

### PR DESCRIPTION
**Pull request by DUFCLiam**
I would like to be a JR.Developer :) (Close if denied/Merge if accepted)

### CODE REVIEW

**Comment by aggelosQQ** [comment]
I'd love you as a developer. :)
@OutOfYourMind

**Comment by DUFCLiam** [comment]
Thanks @aggelosQQ :) I would like to be a developer as well!

**Comment by aggelosQQ** [comment]
of course you'd like to lol
it's immafreedom huh

**Comment by LegendIsAwesomes** [comment]
Well; All your PR's are little tiny changes, nothing huge, @OutOfYourMind I want to let him make bigger changes with big clumps of good, useful code.

**Comment by DUFCLiam** [comment]
@aggelosQQ Well nah.... xD :P Best server ever

@LegendIsAwesomes Ok, Please suggest things I will make them for you :)

**Comment by LegendIsAwesomes** [comment]
Just fix issues @DUFCLiam

**Pull request closed without merging**
