### PR TITLE
Some edits I made

### PR DESCRIPTION
**Pull request by aggelosQQ**
merge if they're fine
@ImmaFreedom-Dev/leaders @ImmaFreedom-Dev/member

### CODE REVIEW

**Comment by OxLemonxO** [comment]
can't merge.

**Comment by tylerhyperHD** [comment]
Will merge this afternoon

**Comment by tylerhyperHD** [comment]
Please make the correct revisions before I merge this request.

**Comment by aggelosQQ** [comment]
@tylerhyperHD, done. :smile:

**Comment by tylerhyperHD** [comment]
Again needs changes

**Comment by LegendIsAwesomes** [comment]
Changes have to be made, @aggelosQQ, Once made this will not be added for version 3.0 but version 3.1, This is because version 3.0 should have come out a very long time ago, though it hasn't. Once changes have been made, it will be merged for version 3.1. 

Though thank you for contributing.

**Comment by aggelosQQ** [comment]
Done

**Comment by LegendIsAwesomes** [comment]
Thank you for contributing this has just been merged.

**Comment by LegendIsAwesomes** [comment]
Needs changes.

**Comment by aggelosQQ** [comment]
Like...?

**Comment by tylerhyperHD** [comment]
Unmergeable, cannot merge to that extent, closed unfortunately.

**Pull request closed without merging**
