### PR TITLE
Create Command_kick.java

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by LegendIsAwesomes** [comment]
Our kick currently is fine.

**Comment by aggelosQQ** [comment]
@LegendIsAwesomes No, I would love a new custom /kick command.

**Comment by LegendIsAwesomes** [comment]
Well, there is things wrong with this.

**Comment by aggelosQQ** [comment]
Create another one then.

**Comment by DUFCLiam** [comment]
@LegendIsAwesomes may you specify what is wrong with this command?

**Pull request closed without merging**
