### PR TITLE
Command_unloadchunks (PR #2)

### PR DESCRIPTION
**Pull request by DUFCLiam**
Continues #87

### CODE REVIEW

**Comment by aggelosQQ** [comment]
@OxLemonxO @RobinGall2910 @LegendIsAwesomes

**Comment by LegendIsAwesomes** [comment]
I'm reviewing this @aggelosqq

**Comment by DUFCLiam** [comment]
@xItsNickHD What changes are needed?

**Comment by aggelosQQ** [comment]
@DUFCLiam, wait for staffers to approve the request before merging it.

**Comment by DUFCLiam** [comment]
Ok, Reverted

**Pull request merged**
