### PR TITLE
Update Command_overlord.java

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by aggelosQQ** [comment]
We don't really use that command, however, okay:P

**Comment by DUFCLiam** [comment]
Is this a merge xD :P I know but still best have it in the case it is needed.

**Comment by aggelosQQ** [comment]
I don't merge things, I am not a developer.

**Comment by LegendIsAwesomes** [comment]
I don't want this, it says OK so console/telnet users see it as a msg, not someone using /overlord, it is meant to be completely hidden, thats why it says ok.

**Comment by DUFCLiam** [comment]
@LegendIsAwesomes, You can only see it if you have permission. Aka has your IP in "overlord_ips:" if it is not in there it says "Unknown command. Type "/help" for help."

**Pull request closed without merging**
