### PR TITLE
Command_ifm.java update

### PR DESCRIPTION
**Pull request by XGreenPlayz12**
Updated the current developer list in /ifm. Changed color on developer list(CReated by"/ Edited by:) to ChatColor.BLUE

Code below

`<code snip>`

### CODE REVIEW

**Comment by DUFCLiam** [comment]
Needs an issue will be re-opned when you have an issue

**Comment by aggelosQQ** [comment]
You can't just remove Tyler, he helped a lot.

**Comment by DUFCLiam** [comment]
Exactly....

**Comment by LegendIsAwesomes** [comment]
Plus @DUFCLiam Shouldn't be on it, Only the main developers who committed a lot should.

**Comment by XGreenPlayz12** [comment]
My bad, i though i could've remove him since he was suspended. Revoke my request.

**Comment by DUFCLiam** [comment]
We have it's fine.

**Pull request closed without merging**
