### PR TITLE
Create Command_unloadchunks.java

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by LegendIsAwesomes** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/pull/674 completely copied, denied, only use your own work

**Comment by DUFCLiam** [comment]
I know I never said it was my code. but I never said it wasn't I thought it would be a nice addition.

**Comment by aggelosQQ** [comment]
I do like this, however, are you sure we are allowed to add this?

**Comment by LegendIsAwesomes** [comment]
1. Copyright
2. This could cause severe server lag when the command is ran it could also crash the server.

**Comment by DUFCLiam** [comment]
Ok, :) Branch deleted.

**Comment by OxLemonxO** [comment]
@LegendIsAwesomes I don't think you understand copyright..... 
Plus this would reduce lag, not increase

**Comment by DUFCLiam** [comment]
@OxLemonxO Do you want me to Restore the branch?

**Comment by LegendIsAwesomes** [comment]
@OxLemonxO I do understand it, I was thinking of other ways then, (I was at school trying not to get caught on my phone xD) yes @DUFCLiam restore it

**Comment by DUFCLiam** [comment]
I cannot restore it, I will create another PR :)

**Pull request closed without merging**
