### PR TITLE
Update Command_doom.java

### PR DESCRIPTION
**Pull request by FoxIshDaBest**
Hello. I suggest not having the SorceType.BOTH for the doom command as lower ranking admins can /gcmd a senior.

### CODE REVIEW

**Comment by aggelosQQ** [comment]
We should trust our admins, shouldn't we? If somebody does this to a senior, it is guaranteed that the senior is going to suspend him.

**Comment by LegendIsAwesomes** [comment]
You can't /gcmd a admin, so no thanks.

**Comment by aggelosQQ** [comment]
@LegendIsAwesomes why not?

**Comment by LegendIsAwesomes** [comment]
What if the senior cannot get to console in time? Only seniors can use it so both should be fine.

**Comment by OutOfYourMind** [comment]
I denied this. It isn't necessary, I already have a pull request for a gcmd update, and this isn't necessary like I said. Seniors need to be able to react quickly to a rogue or abusing administrator if a suspension is necessary. They should be able to do it via in-game or telnet.

**Pull request closed without merging**
