### PR TITLE
Update Command_tag.java

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by aggelosQQ** [comment]
I see a typo > line 135

**Comment by aggelosQQ** [comment]
Could you change this line to something like this
[AutoSmite] You are not an administrator therefore you may not use that tag!

**Comment by DUFCLiam** [comment]
@aggelosQQ, Done.

**Comment by DUFCLiam** [comment]
@OutOfYourMind, May you take a look at this :+1:

**Comment by DUFCLiam** [comment]
@LegendIsAwesomes ?

**Comment by tylerhyperHD** [comment]
This method is internally broken so the string you are editing will not work. Unfortunately I would have to do some more changes to do it so this is closed.

**Comment by DUFCLiam** [comment]
Aww

**Pull request closed without merging**
