### PR TITLE
Update Command_warn.java

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by LegendIsAwesomes** [comment]
WTF? No.

**Comment by DUFCLiam** [comment]
What?

**Comment by DUFCLiam** [comment]
Read all the code.

**Comment by LegendIsAwesomes** [comment]
I did there's literally no point in this

**Comment by DUFCLiam** [comment]
Well, It's a nice feature so people know there warning level.

**Comment by LegendIsAwesomes** [comment]
I understand what your trying to do, I'll do this alone later you did this completely wrong

**Comment by DUFCLiam** [comment]
Ahh, May you comment on the parts that are wrong I done it quick

**Comment by LegendIsAwesomes** [comment]
I want this as a separate command.

**Comment by DUFCLiam** [comment]
I will go do that :) Will it be called "Command_warnlevel.java"? Tell me the name you want

**Comment by LegendIsAwesomes** [comment]
Yes, /warnlevelm

**Comment by LegendIsAwesomes** [comment]
Without the m at the end.

**Comment by DUFCLiam** [comment]
Done @LegendIsAwesomes

**Pull request closed without merging**
