### PR TITLE
Create Command_kick.java

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by aggelosQQ** [comment]
/kick -a is already a command which is already implemented onto TFM. It's /kicknoob.

**Comment by DUFCLiam** [comment]
Removing.

**Comment by DUFCLiam** [comment]
OFT @aggelosQQ, May you review my application I forgot my date that I registered so I am eligible to apply.

**Comment by DUFCLiam** [comment]
@tylerhyperHD, @LegendIsAwesomes, @OutOfYourMind

**Comment by tylerhyperHD** [comment]
Denied as this command has already been implemented.

**Pull request closed without merging**
